# @changed 2025.03.21, 22:08
# @see https://eslint.org/docs/rules/
root: true
extends:
  - 'eslint:recommended'
env:
  es6: true
  commonjs: true
rules:
  no-console: warn
  no-debugger: warn
  no-extra-semi: warn
  no-redeclare: warn
  no-undef: error
  no-unreachable: warn
  prefer-const: warn
  no-empty: warn
  quotes:
    - warn
    - single
  semi:
    - warn
    - always

overrides:
  - # Typescript files (ts,tsx)...
    files: '**/*.+(ts|tsx)'
    extends:
      - 'eslint:recommended'
      - 'plugin:prettier/recommended' # prettier: Slighly slower (+0.3s)
      - 'plugin:@typescript-eslint/recommended'
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: 12
      sourceType: 'module'
    plugins:
      - '@typescript-eslint'
      - 'prettier' # prettier: Slighly slower (+~0.3s)
    rules:
      no-undef: 'off' # Disable js no-undef rule for typescript sources. Using ts2304 instead.
      no-debugger: 'warn'
      prettier/prettier: # prettier: Slighly slower (+0.3s)
        - 'warn' # Can we to use warn if we still use `eslint --max-warnings=0` in `package.json`?
        - endOfLine: 'auto'
      import/no-namespace: 'off'
      no-unused-vars: 'off'
      '@typescript-eslint/explicit-member-accessibility':
        - 'error'
        - accessibility: 'no-public'
      '@typescript-eslint/no-unused-vars':
        - 'warn'
        - # varsIgnorePattern: '^[T][A-Z]\\w+' # M.b. useful for typescript `TSmth` types: eslint may treat them us 'unused'.
          varsIgnorePattern: '^_'
          argsIgnorePattern: '^_'
      '@typescript-eslint/no-require-imports': 'warn'
      '@typescript-eslint/array-type': 'error'
      '@typescript-eslint/ban-ts-comment':
        - 'error'
        - ts-ignore: 'allow-with-description'
      '@typescript-eslint/naming-convention':
        - 'error'
        - selector: 'function'
          format:
            - 'PascalCase'
            - 'camelCase'
      '@typescript-eslint/explicit-module-boundary-types': 'off' # Disable 'Missing return type on function' if no explicit `: void` specified
      '@typescript-eslint/explicit-function-return-type': 0 # Causes 'Missing return type on function' if no explicit `: void` specified
      '@typescript-eslint/func-call-spacing':
        - 'error'
        - 'never'
      '@typescript-eslint/no-explicit-any': 'warn'
      '@typescript-eslint/no-extraneous-class':
        - 'error'
        - allowStaticOnly: true
      '@typescript-eslint/no-non-null-assertion': 'warn'
      '@typescript-eslint/no-useless-constructor': 'error'
      '@typescript-eslint/prefer-for-of': 'warn'
      '@typescript-eslint/prefer-function-type': 'warn'
      '@typescript-eslint/consistent-type-definitions': 'error'
      '@typescript-eslint/type-annotation-spacing': 'error'

  - # Raw js files (from root)...
    files: '**/*.js'
    parser: '@babel/eslint-parser'
    env:
      node: true
      commonjs: true
      es6: true
    extends:
      - 'eslint:recommended'
      - 'plugin:prettier/recommended'
      # - 'plugin:import/recommended'
    plugins:
      - 'prettier' # prettier: Slighly slower (+~0.3s)
    rules:
      prettier/prettier: 'warn'
      no-unused-vars:
        - 'warn'
        - argsIgnorePattern: '^_'
      no-console: 'warn'
      no-debugger: 'warn'
      no-extra-semi: 'warn'
      no-redeclare: 'warn'
      no-undef: 'error'
      no-unreachable: 'warn'
      prefer-const: 'warn'
      semi:
        - 'warn'
        - 'always'

  - # Raw js project files...
    files: 'src/**/*.js'
    # parser: '@babel/eslint-parser'
    parser: null
    env:
      es6: true
      browser: true
    globals:
      modules: true
    extends:
      - 'eslint:recommended'
      - 'plugin:prettier/recommended'
    plugins:
      - 'prettier' # prettier: Slighly slower (+~0.3s)
    rules:
      no-var: 'warn'
      prettier/prettier: 'warn'
      no-unused-vars:
        - 'warn'
        - argsIgnorePattern: '^_'
      no-console: 'warn'
      no-debugger: 'warn'
      no-extra-semi: 'warn'
      no-redeclare: 'warn'
      no-undef: 'error'
      no-unreachable: 'warn'
      prefer-const: 'warn'
      semi:
        - 'warn'
        - 'always'

  - # Raw mjs files (from root)...
    files: '**/*.mjs'
    parser: '@babel/eslint-parser'
    parserOptions:
      sourceType: 'module'
    env:
      node: true
      es6: true
    extends:
      - 'eslint:recommended'
      - 'plugin:prettier/recommended'
      - 'plugin:import/recommended'
    plugins:
      - 'prettier' # prettier: Slighly slower (+~0.3s)
    rules:
      prettier/prettier: 'warn'
      no-unused-vars:
        - 'warn'
        - argsIgnorePattern: '^_'
      no-console: 'warn'
      no-debugger: 'warn'
      no-extra-semi: 'warn'
      no-redeclare: 'warn'
      no-undef: 'error'
      no-unreachable: 'warn'
      prefer-const: 'warn'
      semi:
        - 'warn'
        - 'always'

  - # json files (@see https://www.npmjs.com/package/eslint-plugin-json)...
    files: '**/*.json'
    extends:
      - 'plugin:json/recommended'
    rules:
      prettier/prettier: 'warn'

  - # jsonc files - commented json (@see https://www.npmjs.com/package/eslint-plugin-jsonc)...
    files: '**/*.jsonc'
    extends:
      - 'plugin:jsonc/recommended-with-jsonc'
    rules:
      prettier/prettier: 'warn'
